-- supabase/migrations/00064_extend_country_catalog.sql
-- Extends the country content catalog:
--   1. Adds extra column schema (code3, currency_code, nationality, phone_prefix, domain, i18n)
--   2. Replaces the limited 20-item list with a comprehensive 200+ country list

-- Step 1: Set extra column schema on the country catalog
UPDATE public.content_catalogs
SET columns = '{
  "columns": [
    {"key": "code3",         "label": "ISO Alpha-3",    "type": "text", "description": "3-character ISO 3166-1 alpha-3 code (e.g. MYS)"},
    {"key": "currency_code", "label": "Currency Code",  "type": "text", "description": "ISO 4217 currency code (e.g. MYR)"},
    {"key": "nationality",   "label": "Nationality",    "type": "text", "description": "Demonym(s), comma-separated if multiple"},
    {"key": "phone_prefix",  "label": "Phone Prefix",   "type": "text", "description": "International dialing prefix (e.g. +60)"},
    {"key": "domain",        "label": "Domain",         "type": "text", "description": "Country-code top-level domain (e.g. .my)"},
    {"key": "i18n",          "label": "Languages",      "type": "text", "description": "ISO 639-1 language codes, comma-separated"}
  ]
}'::jsonb
WHERE slug = 'country';

-- Step 2: Remove existing items
DELETE FROM public.content_catalog_items
WHERE catalog_id = (SELECT id FROM public.content_catalogs WHERE slug = 'country');

-- Step 3: Insert comprehensive country list (200+ entries, alphabetical by label)
INSERT INTO public.content_catalog_items (catalog_id, value, label, sort_order, data)
SELECT
  c.id,
  v.alpha2,
  v.name,
  ROW_NUMBER() OVER (ORDER BY v.name) AS sort_order,
  jsonb_build_object(
    'code3',         v.alpha3,
    'currency_code', v.currency,
    'nationality',   v.nationality,
    'phone_prefix',  v.phone,
    'domain',        v.domain,
    'i18n',          v.i18n
  ) AS data
FROM public.content_catalogs c,
(VALUES
  ('AF','Afghanistan',          'AFG','AFN','Afghan',                '+93',    '.af','ps,fa'),
  ('AL','Albania',              'ALB','ALL','Albanian',              '+355',   '.al','sq'),
  ('DZ','Algeria',              'DZA','DZD','Algerian',              '+213',   '.dz','ar,fr'),
  ('AD','Andorra',              'AND','EUR','Andorran',              '+376',   '.ad','ca'),
  ('AO','Angola',               'AGO','AOA','Angolan',               '+244',   '.ao','pt'),
  ('AG','Antigua and Barbuda',  'ATG','XCD','Antiguan,Barbudan',     '+1-268', '.ag','en'),
  ('AR','Argentina',            'ARG','ARS','Argentine',             '+54',    '.ar','es'),
  ('AM','Armenia',              'ARM','AMD','Armenian',              '+374',   '.am','hy'),
  ('AW','Aruba',                'ABW','AWG','Aruban',                '+297',   '.aw','nl,pap'),
  ('AU','Australia',            'AUS','AUD','Australian',            '+61',    '.au','en'),
  ('AT','Austria',              'AUT','EUR','Austrian',              '+43',    '.at','de'),
  ('AZ','Azerbaijan',           'AZE','AZN','Azerbaijani',           '+994',   '.az','az'),
  ('BS','Bahamas',              'BHS','BSD','Bahamian',              '+1-242', '.bs','en'),
  ('BH','Bahrain',              'BHR','BHD','Bahraini',              '+973',   '.bh','ar'),
  ('BD','Bangladesh',           'BGD','BDT','Bangladeshi',           '+880',   '.bd','bn'),
  ('BB','Barbados',             'BRB','BBD','Barbadian',             '+1-246', '.bb','en'),
  ('BY','Belarus',              'BLR','BYR','Belarusian',            '+375',   '.by','be,ru'),
  ('BE','Belgium',              'BEL','EUR','Belgian',               '+32',    '.be','nl,fr,de'),
  ('BZ','Belize',               'BLZ','BZD','Belizean',              '+501',   '.bz','en'),
  ('BJ','Benin',                'BEN','XOF','Beninese',              '+229',   '.bj','fr'),
  ('BT','Bhutan',               'BTN','BTN','Bhutanese',             '+975',   '.bt','dz'),
  ('BO','Bolivia',              'BOL','BOB','Bolivian',              '+591',   '.bo','es'),
  ('BA','Bosnia and Herzegovina','BIH','BAM','Bosnian,Herzegovinian','+387',   '.ba','bs,hr,sr'),
  ('BW','Botswana',             'BWA','BWP','Motswana',              '+267',   '.bw','en,tn'),
  ('BR','Brazil',               'BRA','BRL','Brazilian',             '+55',    '.br','pt'),
  ('BN','Brunei',               'BRN','BND','Bruneian',              '+673',   '.bn','ms'),
  ('BG','Bulgaria',             'BGR','BGN','Bulgarian',             '+359',   '.bg','bg'),
  ('BF','Burkina Faso',         'BFA','XOF','Burkinabe',             '+226',   '.bf','fr'),
  ('BI','Burundi',              'BDI','BIF','Burundian',             '+257',   '.bi','fr,rn'),
  ('CV','Cabo Verde',           'CPV','CVE','Cape Verdean',          '+238',   '.cv','pt'),
  ('KH','Cambodia',             'KHM','KHR','Cambodian',             '+855',   '.kh','km'),
  ('CM','Cameroon',             'CMR','XAF','Cameroonian',           '+237',   '.cm','fr,en'),
  ('CA','Canada',               'CAN','CAD','Canadian',              '+1',     '.ca','en,fr'),
  ('CF','Central African Republic','CAF','XAF','Central African',   '+236',   '.cf','fr,sg'),
  ('TD','Chad',                 'TCD','XAF','Chadian',               '+235',   '.td','fr,ar'),
  ('CL','Chile',                'CHL','CLP','Chilean',               '+56',    '.cl','es'),
  ('CN','China',                'CHN','CNY','Chinese',               '+86',    '.cn','zh'),
  ('CO','Colombia',             'COL','COP','Colombian',             '+57',    '.co','es'),
  ('KM','Comoros',              'COM','KMF','Comorian',              '+269',   '.km','ar,fr,sw'),
  ('CD','Congo (DRC)',          'COD','CDF','Congolese',             '+243',   '.cd','fr'),
  ('CG','Congo (Republic)',     'COG','XAF','Congolese',             '+242',   '.cg','fr'),
  ('CR','Costa Rica',           'CRI','CRC','Costa Rican',           '+506',   '.cr','es'),
  ('HR','Croatia',              'HRV','EUR','Croatian',              '+385',   '.hr','hr'),
  ('CU','Cuba',                 'CUB','CUP','Cuban',                 '+53',    '.cu','es'),
  ('CW','Curaçao',              'CUW','ANG','Curaçaoan',             '+599',   '.cw','nl,pap,en'),
  ('CY','Cyprus',               'CYP','EUR','Cypriot',               '+357',   '.cy','el,tr'),
  ('CZ','Czech Republic',       'CZE','CZK','Czech',                 '+420',   '.cz','cs'),
  ('DK','Denmark',              'DNK','DKK','Danish',                '+45',    '.dk','da'),
  ('DJ','Djibouti',             'DJI','DJF','Djiboutian',            '+253',   '.dj','fr,ar'),
  ('DM','Dominica',             'DMA','XCD','Dominican',             '+1-767', '.dm','en'),
  ('DO','Dominican Republic',   'DOM','DOP','Dominican',             '+1-809', '.do','es'),
  ('EC','Ecuador',              'ECU','USD','Ecuadorian',             '+593',   '.ec','es'),
  ('EG','Egypt',                'EGY','EGP','Egyptian',              '+20',    '.eg','ar'),
  ('SV','El Salvador',          'SLV','USD','Salvadoran',            '+503',   '.sv','es'),
  ('GQ','Equatorial Guinea',    'GNQ','XAF','Equatoguinean',         '+240',   '.gq','es,fr,pt'),
  ('ER','Eritrea',              'ERI','ERN','Eritrean',              '+291',   '.er','ti,ar,en'),
  ('EE','Estonia',              'EST','EUR','Estonian',              '+372',   '.ee','et'),
  ('SZ','Eswatini',             'SWZ','SZL','Swazi',                 '+268',   '.sz','ss,en'),
  ('ET','Ethiopia',             'ETH','ETB','Ethiopian',             '+251',   '.et','am'),
  ('FO','Faroe Islands',        'FRO','DKK','Faroese',               '+298',   '.fo','fo,da'),
  ('FJ','Fiji',                 'FJI','FJD','Fijian',                '+679',   '.fj','en,fj'),
  ('FI','Finland',              'FIN','EUR','Finnish',               '+358',   '.fi','fi,sv'),
  ('FR','France',               'FRA','EUR','French',                '+33',    '.fr','fr'),
  ('GA','Gabon',                'GAB','XAF','Gabonese',              '+241',   '.ga','fr'),
  ('GM','Gambia',               'GMB','GMD','Gambian',               '+220',   '.gm','en'),
  ('GE','Georgia',              'GEO','GEL','Georgian',              '+995',   '.ge','ka'),
  ('DE','Germany',              'DEU','EUR','German',                '+49',    '.de','de'),
  ('GH','Ghana',                'GHA','GHS','Ghanaian',              '+233',   '.gh','en'),
  ('GI','Gibraltar',            'GIB','GIP','Gibraltarian',          '+350',   '.gi','en'),
  ('GR','Greece',               'GRC','EUR','Greek',                 '+30',    '.gr','el'),
  ('GD','Grenada',              'GRD','XCD','Grenadian',             '+1-473', '.gd','en'),
  ('GT','Guatemala',            'GTM','GTQ','Guatemalan',            '+502',   '.gt','es'),
  ('GN','Guinea',               'GIN','GNF','Guinean',               '+224',   '.gn','fr'),
  ('GW','Guinea-Bissau',        'GNB','XOF','Bissau-Guinean',        '+245',   '.gw','pt'),
  ('GY','Guyana',               'GUY','GYD','Guyanese',              '+592',   '.gy','en'),
  ('HT','Haiti',                'HTI','HTG','Haitian',               '+509',   '.ht','fr,ht'),
  ('HN','Honduras',             'HND','HNL','Honduran',              '+504',   '.hn','es'),
  ('HK','Hong Kong',            'HKG','HKD','Hong Konger',           '+852',   '.hk','zh,en'),
  ('HU','Hungary',              'HUN','HUF','Hungarian',             '+36',    '.hu','hu'),
  ('IS','Iceland',              'ISL','ISK','Icelandic',             '+354',   '.is','is'),
  ('IN','India',                'IND','INR','Indian',                '+91',    '.in','hi,en'),
  ('ID','Indonesia',            'IDN','IDR','Indonesian',            '+62',    '.id','id'),
  ('IR','Iran',                 'IRN','IRR','Iranian',               '+98',    '.ir','fa'),
  ('IQ','Iraq',                 'IRQ','IQD','Iraqi',                 '+964',   '.iq','ar,ku'),
  ('IE','Ireland',              'IRL','EUR','Irish',                 '+353',   '.ie','en,ga'),
  ('IL','Israel',               'ISR','ILS','Israeli',               '+972',   '.il','he,ar'),
  ('IT','Italy',                'ITA','EUR','Italian',               '+39',    '.it','it'),
  ('JM','Jamaica',              'JAM','JMD','Jamaican',              '+1-876', '.jm','en'),
  ('JP','Japan',                'JPN','JPY','Japanese',              '+81',    '.jp','ja'),
  ('JO','Jordan',               'JOR','JOD','Jordanian',             '+962',   '.jo','ar'),
  ('KZ','Kazakhstan',           'KAZ','KZT','Kazakhstani',           '+7',     '.kz','kk,ru'),
  ('KE','Kenya',                'KEN','KES','Kenyan',                '+254',   '.ke','sw,en'),
  ('KI','Kiribati',             'KIR','AUD','I-Kiribati',            '+686',   '.ki','en'),
  ('XK','Kosovo',               'XKX','EUR','Kosovar',               '+383',   '.xk','sq,sr'),
  ('KW','Kuwait',               'KWT','KWD','Kuwaiti',               '+965',   '.kw','ar'),
  ('KG','Kyrgyzstan',           'KGZ','KGS','Kyrgyz',                '+996',   '.kg','ky,ru'),
  ('LA','Laos',                 'LAO','LAK','Lao',                   '+856',   '.la','lo'),
  ('LV','Latvia',               'LVA','EUR','Latvian',               '+371',   '.lv','lv'),
  ('LB','Lebanon',              'LBN','LBP','Lebanese',              '+961',   '.lb','ar,fr'),
  ('LS','Lesotho',              'LSO','LSL','Basotho',               '+266',   '.ls','st,en'),
  ('LR','Liberia',              'LBR','LRD','Liberian',              '+231',   '.lr','en'),
  ('LY','Libya',                'LBY','LYD','Libyan',                '+218',   '.ly','ar'),
  ('LI','Liechtenstein',        'LIE','CHF','Liechtensteiner',       '+423',   '.li','de'),
  ('LT','Lithuania',            'LTU','EUR','Lithuanian',            '+370',   '.lt','lt'),
  ('LU','Luxembourg',           'LUX','EUR','Luxembourger',          '+352',   '.lu','fr,de,lb'),
  ('MO','Macau',                'MAC','MOP','Macanese',              '+853',   '.mo','zh,pt'),
  ('MG','Madagascar',           'MDG','MGA','Malagasy',              '+261',   '.mg','mg,fr'),
  ('MW','Malawi',               'MWI','MWK','Malawian',              '+265',   '.mw','en,ny'),
  ('MY','Malaysia',             'MYS','MYR','Malaysian',             '+60',    '.my','ms'),
  ('MV','Maldives',             'MDV','MVR','Maldivian',             '+960',   '.mv','dv'),
  ('ML','Mali',                 'MLI','XOF','Malian',                '+223',   '.ml','fr'),
  ('MT','Malta',                'MLT','EUR','Maltese',               '+356',   '.mt','mt,en'),
  ('MH','Marshall Islands',     'MHL','USD','Marshallese',           '+692',   '.mh','en,mh'),
  ('MR','Mauritania',           'MRT','MRU','Mauritanian',           '+222',   '.mr','ar'),
  ('MU','Mauritius',            'MUS','MUR','Mauritian',             '+230',   '.mu','en,fr'),
  ('MX','Mexico',               'MEX','MXN','Mexican',               '+52',    '.mx','es'),
  ('FM','Micronesia',           'FSM','USD','Micronesian',            '+691',   '.fm','en'),
  ('MD','Moldova',              'MDA','MDL','Moldovan',              '+373',   '.md','ro'),
  ('MC','Monaco',               'MCO','EUR','Monegasque',            '+377',   '.mc','fr'),
  ('MN','Mongolia',             'MNG','MNT','Mongolian',             '+976',   '.mn','mn'),
  ('ME','Montenegro',           'MNE','EUR','Montenegrin',           '+382',   '.me','sr'),
  ('MA','Morocco',              'MAR','MAD','Moroccan',              '+212',   '.ma','ar,fr'),
  ('MZ','Mozambique',           'MOZ','MZN','Mozambican',            '+258',   '.mz','pt'),
  ('MM','Myanmar',              'MMR','MMK','Burmese',               '+95',    '.mm','my'),
  ('NA','Namibia',              'NAM','NAD','Namibian',              '+264',   '.na','en'),
  ('NR','Nauru',                'NRU','AUD','Nauruan',               '+674',   '.nr','na,en'),
  ('NP','Nepal',                'NPL','NPR','Nepali',                '+977',   '.np','ne'),
  ('NL','Netherlands',          'NLD','EUR','Dutch',                 '+31',    '.nl','nl'),
  ('NZ','New Zealand',          'NZL','NZD','New Zealander',         '+64',    '.nz','en,mi'),
  ('NI','Nicaragua',            'NIC','NIO','Nicaraguan',            '+505',   '.ni','es'),
  ('NE','Niger',                'NER','XOF','Nigerien',              '+227',   '.ne','fr'),
  ('NG','Nigeria',              'NGA','NGN','Nigerian',              '+234',   '.ng','en'),
  ('MK','North Macedonia',      'MKD','MKD','Macedonian',            '+389',   '.mk','mk,sq'),
  ('KP','North Korea',          'PRK','KPW','North Korean',          '+850',   '.kp','ko'),
  ('NO','Norway',               'NOR','NOK','Norwegian',             '+47',    '.no','nb,nn'),
  ('OM','Oman',                 'OMN','OMR','Omani',                 '+968',   '.om','ar'),
  ('PK','Pakistan',             'PAK','PKR','Pakistani',             '+92',    '.pk','ur,en'),
  ('PW','Palau',                'PLW','USD','Palauan',               '+680',   '.pw','en,pau'),
  ('PS','Palestine',            'PSE','ILS','Palestinian',           '+970',   '.ps','ar'),
  ('PA','Panama',               'PAN','PAB','Panamanian',            '+507',   '.pa','es'),
  ('PG','Papua New Guinea',     'PNG','PGK','Papua New Guinean',     '+675',   '.pg','en,ho,tpi'),
  ('PY','Paraguay',             'PRY','PYG','Paraguayan',            '+595',   '.py','es,gn'),
  ('PE','Peru',                 'PER','PEN','Peruvian',              '+51',    '.pe','es'),
  ('PH','Philippines',          'PHL','PHP','Filipino',              '+63',    '.ph','fil,en'),
  ('PL','Poland',               'POL','PLN','Polish',                '+48',    '.pl','pl'),
  ('PT','Portugal',             'PRT','EUR','Portuguese',            '+351',   '.pt','pt'),
  ('QA','Qatar',                'QAT','QAR','Qatari',                '+974',   '.qa','ar'),
  ('RO','Romania',              'ROU','RON','Romanian',              '+40',    '.ro','ro'),
  ('RU','Russia',               'RUS','RUB','Russian',               '+7',     '.ru','ru'),
  ('RW','Rwanda',               'RWA','RWF','Rwandan',               '+250',   '.rw','rw,fr,en'),
  ('KN','Saint Kitts and Nevis','KNA','XCD','Kittitian,Nevisian',    '+1-869', '.kn','en'),
  ('LC','Saint Lucia',          'LCA','XCD','Saint Lucian',          '+1-758', '.lc','en'),
  ('VC','Saint Vincent and the Grenadines','VCT','XCD','Vincentian', '+1-784', '.vc','en'),
  ('WS','Samoa',                'WSM','WST','Samoan',                '+685',   '.ws','sm,en'),
  ('SM','San Marino',           'SMR','EUR','Sammarinese',           '+378',   '.sm','it'),
  ('ST','Sao Tome and Principe','STP','STN','Sao Tomean',            '+239',   '.st','pt'),
  ('SA','Saudi Arabia',         'SAU','SAR','Saudi',                 '+966',   '.sa','ar'),
  ('SN','Senegal',              'SEN','XOF','Senegalese',            '+221',   '.sn','fr'),
  ('RS','Serbia',               'SRB','RSD','Serbian',               '+381',   '.rs','sr'),
  ('SC','Seychelles',           'SYC','SCR','Seychellois',           '+248',   '.sc','en,fr,cs'),
  ('SL','Sierra Leone',         'SLE','SLL','Sierra Leonean',        '+232',   '.sl','en'),
  ('SG','Singapore',            'SGP','SGD','Singaporean',           '+65',    '.sg','en,zh,ms,ta'),
  ('SX','Sint Maarten',         'SXM','ANG','Sint Maartener',        '+1-721', '.sx','en,nl'),
  ('SK','Slovakia',             'SVK','EUR','Slovak',                '+421',   '.sk','sk'),
  ('SI','Slovenia',             'SVN','EUR','Slovenian',             '+386',   '.si','sl'),
  ('SB','Solomon Islands',      'SLB','SBD','Solomon Islander',      '+677',   '.sb','en'),
  ('SO','Somalia',              'SOM','SOS','Somali',                '+252',   '.so','so,ar'),
  ('ZA','South Africa',         'ZAF','ZAR','South African',         '+27',    '.za','af,en,zu,xh,st,tn,ts,ss,ve,nr'),
  ('KR','South Korea',          'KOR','KRW','South Korean',          '+82',    '.kr','ko'),
  ('SS','South Sudan',          'SSD','SSP','South Sudanese',        '+211',   '.ss','en'),
  ('ES','Spain',                'ESP','EUR','Spanish',               '+34',    '.es','es'),
  ('LK','Sri Lanka',            'LKA','LKR','Sri Lankan',            '+94',    '.lk','si,ta'),
  ('SD','Sudan',                'SDN','SDG','Sudanese',              '+249',   '.sd','ar,en'),
  ('SR','Suriname',             'SUR','SRD','Surinamese',            '+597',   '.sr','nl'),
  ('SE','Sweden',               'SWE','SEK','Swedish',               '+46',    '.se','sv'),
  ('CH','Switzerland',          'CHE','CHF','Swiss',                 '+41',    '.ch','de,fr,it,rm'),
  ('SY','Syria',                'SYR','SYP','Syrian',                '+963',   '.sy','ar'),
  ('TW','Taiwan',               'TWN','TWD','Taiwanese',             '+886',   '.tw','zh'),
  ('TJ','Tajikistan',           'TJK','TJS','Tajik',                 '+992',   '.tj','tg,ru'),
  ('TZ','Tanzania',             'TZA','TZS','Tanzanian',             '+255',   '.tz','sw,en'),
  ('TH','Thailand',             'THA','THB','Thai',                  '+66',    '.th','th'),
  ('TL','Timor-Leste',          'TLS','USD','Timorese',              '+670',   '.tl','pt,tet'),
  ('TG','Togo',                 'TGO','XOF','Togolese',              '+228',   '.tg','fr'),
  ('TO','Tonga',                'TON','TOP','Tongan',                '+676',   '.to','en,to'),
  ('TT','Trinidad and Tobago',  'TTO','TTD','Trinidadian,Tobagonian','+1-868', '.tt','en'),
  ('TN','Tunisia',              'TUN','TND','Tunisian',              '+216',   '.tn','ar,fr'),
  ('TR','Türkiye',              'TUR','TRY','Turkish',               '+90',    '.tr','tr'),
  ('TM','Turkmenistan',         'TKM','TMT','Turkmen',               '+993',   '.tm','tk'),
  ('TV','Tuvalu',               'TUV','AUD','Tuvaluan',              '+688',   '.tv','en,tvl'),
  ('UG','Uganda',               'UGA','UGX','Ugandan',               '+256',   '.ug','en,sw'),
  ('UA','Ukraine',              'UKR','UAH','Ukrainian',             '+380',   '.ua','uk'),
  ('AE','United Arab Emirates', 'ARE','AED','Emirati',               '+971',   '.ae','ar'),
  ('GB','United Kingdom',       'GBR','GBP','British',               '+44',    '.uk','en'),
  ('US','United States',        'USA','USD','American',               '+1',     '.us','en'),
  ('UY','Uruguay',              'URY','UYU','Uruguayan',             '+598',   '.uy','es'),
  ('UZ','Uzbekistan',           'UZB','UZS','Uzbek',                 '+998',   '.uz','uz,ru'),
  ('VU','Vanuatu',              'VUT','VUV','Vanuatuan',             '+678',   '.vu','bi,en,fr'),
  ('VA','Vatican City',         'VAT','EUR','Vatican',               '+39',    '.va','it,la'),
  ('VE','Venezuela',            'VEN','VES','Venezuelan',            '+58',    '.ve','es'),
  ('VN','Vietnam',              'VNM','VND','Vietnamese',            '+84',    '.vn','vi'),
  ('YE','Yemen',                'YEM','YER','Yemeni',                '+967',   '.ye','ar'),
  ('ZM','Zambia',               'ZMB','ZMW','Zambian',               '+260',   '.zm','en'),
  ('ZW','Zimbabwe',             'ZWE','ZWL','Zimbabwean',            '+263',   '.zw','en,sn,nd')
) AS v(alpha2, name, alpha3, currency, nationality, phone, domain, i18n)
WHERE c.slug = 'country';
